### ISSUE TITLE
When I try to run Shortcutes.exe it wants me to open Windows Store trying on ROG Ally

### ISSUE THREAD

**Issue by Elrinth** [Haruki1707/ShortCutes#10]
It says: "Would you like to search for an app in store? - You need to install an app for this task. Would you like to search for an app in Store?"

Any clue why this is? And on Microsoft Store it just shows an empty broken page.

**Comment by Elrinth** [comment]
no. I install .NET 3.5 also... Now I have 2.0, 3.0, 3.5, 4 and 4.8. Same as on my stationary desktop. This only happens on the ASUS ROG Ally...

**Comment by Haruki1707** [comment]
Yes, if after building it yourself worked, seems like the antivirus could be the problem, that's why is better to make an exception. I will close the issue and take it as a possible solution for the future. TY.
