### ISSUE TITLE
Duckstation "The specified savestate does not exist."

### ISSUE THREAD

**Issue by Shockrocketisnotavailable** [Haruki1707/ShortCutes#11]
Whenever I launch a shortcut to a PSX game that uses Duckstation, it keeps telling me that "The specified savestate does not exist". Happens with the 2 PSX games I tested, Crash Bandicoot, and Rayman (both being the US versions).

Here is some additional info:

- Duckstation is located in C:\Users\rudej\Downloads\duckstation-windows-x64-release
- The bin/cue files are located in C:\Users\rudej\Downloads\ROMS AT NO COST, SATISFACTORY\SONY\PS1 (Rayman and Crash being in the folders called "Rayman (USA)", and "Crash Bandicoot (USA)" respectively.)
- I'm using the latest version of both ShortCutes, and Duckstation.

**Comment by Haruki1707** [comment]
Try starting the games directly from DuckStation, then in System do a Power Off and save a state, after that try starting it from the ShortCute, if that doesn't work is cause it has something to do with your save states not being save correctly. You could try to fix that or either disable the save states.

**Comment by Shockrocketisnotavailable** [comment]
Tried that, and it works, thank you!
