### ISSUE TITLE
Launching Shortcutes doesn't work, nothing happens.

### ISSUE THREAD

**Issue by BrochachoTheBro** [Haruki1707/ShortCutes#12]
I used to be able to use Shortcutes just fine on Windows 10, but when I updated to 11, it doesn't work anymore. I try launching it, it asks for permission to launch, and nothing happens after.
I do meet the prerequisites, .NET 4.8 is installed.

**Comment by Haruki1707** [comment]
Someone kind of had the same problem with W11, seemed to be a Antivirus problem, you can either exclude ShortCutes from your Antivirus or compile ShortCutes yourself so your Antivirus doesn't detect has malware.

**Comment by BrochachoTheBro** [comment]
Tried the exclusion method and that didn't work. I'm sorry if this is a noob question, but how could one go about compiling Shortcutes?
