### ISSUE TITLE
PCSX2 command-line when using QT version

### ISSUE THREAD

**Issue by Hippobotus** [Haruki1707/ShortCutes#13]
Hello, 

When using the QT version of PCSX2, there is a slight change in command-line where the double-dash becomes a single-dash.

E.g. _--fullscreen_ becomes _-fullscreen_

E.g. pcsx2.exe "ISO (USA).chd" -batch -fullscreen

More info can be found here: [https://wiki.pcsx2.net/index.php/Command-line_support#General_Options_QT](https://wiki.pcsx2.net/index.php/Command-line_support#General_Options_QT)

**Comment by Haruki1707** [comment]
PCSX2 QT already has the command as '-fullscreen' with a single-dash
