### ISSUE TITLE
Unable to start games using Duckstation

### ISSUE THREAD

**Issue by maximAtanasov** [Haruki1707/ShortCutes#17]
Hello there, love your tool!

Unfortunately, starting games using Duckstation is not working for me, regardless of the game I try. The emulator starts up with the following error: 

`The specified save state does not exist`

I removed the `--resume` flag from the launch parameters and rebuilt the App, which has fixed the issue for me. Could you perhaps explain, why the flag is needed at all and how to get it to work?

**Comment by Haruki1707** [comment]
DuckStation by default when you close a game it makes a save state, maybe you had disabled it and that's why it's not working. But thinking more about it, it should not include the flag by default, I will quit it in the next update.

**Comment by Haruki1707** [comment]
Update released.

**Comment by maximAtanasov** [comment]
Thanks :)
