### ISSUE TITLE
Add support for xenia (Xbox 360 Emulator)

### ISSUE THREAD

**Issue by Erick8x** [Haruki1707/ShortCutes#2]
Parameters are "xenia.exe path-to-game" without comma or tags, normally Xbox 360 games doesn't have a file extension (like Live Arcade games or ripped games), but .iso and .xex are the format games support, but don't put a delimitation for file extension (if possible).

Fullscreen mode needs to user edit the .ini in documents or manually press F11 on game screen.

**Comment by Haruki1707** [comment]
I'm testing xenia support in ShortCutes right now, if everything continues working fine, I will upload an update for ShortCutes
* ShortCutes has an auto-updater, so no need to manually download the new version

About the file delimitation, I will put it also for xbox 360 games, but I added "All files (*.*)" to files option on the explorer as you can see in the picture below.
![image](https://user-images.githubusercontent.com/72423267/165186979-eec2df67-cba5-4366-bda9-ab080d8d5e6f.png)

**Comment by Haruki1707** [comment]
ShortCutes 1.4.2 with Xenia support already released, hope you enjoy it. If any problem don't hesitate to open an Issue
* If you are enjoying this tool, please consider giving a star to the repo, that would help a lot
