### ISSUE TITLE
MelonDS support

### ISSUE THREAD

**Issue by LizandroPL** [Haruki1707/ShortCutes#4]
Any chance to add support to MelonDS? Please!

**Comment by Haruki1707** [comment]
You can already download the newest version with MelonDS added, I will recommend manually downloading the new version as the old one has a problem with auto-updater (already fixed on the newest version) and it will never finish updating.

Any concern or other request, don't hesitate to open an issue

> If you like ShortCutes, consider sharing the tool with others or giving a star to the project, this will help a lot
