### ISSUE TITLE
Citra closes whenever I make a shortcut

### ISSUE THREAD

**Issue by Xeratone** [Haruki1707/ShortCutes#5]
Using a ShortCute will make Citra open momentarily and then quickly close, if I open it with the emulator normally then it functions fine.

**Comment by Haruki1707** [comment]
I will check on it this weekend

**Comment by Haruki1707** [comment]
@Xeratone  I have tested Citra and it works perfectly fine for me as you can see here

https://user-images.githubusercontent.com/72423267/216866028-1456db41-fc0e-4548-9669-933d8ea4fa4f.mp4

To know more about the error and fix the problem you have, can you explain me how is your setup, like:

- Where do you have citra installed
- Where is your game located
- What is the format of the game you are trying to open
- Which version of ShortCutes do you have
- Any other important setting you have on your PC

**Comment by Xeratone** [comment]
1. C:\Users\PC\AppData\Local\Citra\nightly-mingw
2. "D:\Users\PC\Documents\Emulation\Metroid - Samus Returns (USA) (En,Fr,Es).3ds"
3. .3ds
4. The latest one
5. Not that I can think of
