### ISSUE TITLE
Add option to change position/hide ''opening'' window.

### ISSUE THREAD

**Issue by Gonckzilla** [Haruki1707/ShortCutes#6]
Hello! First off, thanks a lot for this utility, using it has been a breeze.

I wonder if you could implement a feature where you can change the loading window positioning (the one that shows up right after opening the created shortcut), so that for example, we could choose the loading window to show up in the corners or the center which is the default right now. 

Related to this same purpose, maybe a hide option would be good too. The reason I'm looking for these alternatives is because I use PCSX2 without system bios skipping, which causes the loading screen to not dismiss until the game rom has been loaded; using the center of the screen in the meanwhile and covering the nostalgic PS2 boot-up animation.

I think it would make a nice addition! And by moving it manually to a corner of the screen, I think it looks pretty cool. 

![Loading screen in corner](https://user-images.githubusercontent.com/70910647/228645953-cfaf2761-43c1-4155-b72b-7443fa7f4173.png)

**Comment by Haruki1707** [comment]
Hi, I'm glad ShortCutes has been useful.

That's a great feature idea, I will try to develop it next week as I will be kinda free.

Also I will check if I can make sure that bios skipping is disabled so the window hides automatically before the animation starts.

**Comment by Haruki1707** [comment]
Hi @Gonckzilla

I managed to do it, it got me some time cause I did it in two ways, one is a checkbox so you can force the close of the launcher once any emulator opens

![image](https://user-images.githubusercontent.com/72423267/232265003-4c205358-fb93-4461-bbe3-41d92931b384.png)

The other one is specially made for your case, in this one you don't have to check any option, it will detect that is PCSX2, and it will read it's configuration looking for the option of BIOS animation skip, in case the option is disable it will force the launcher to close. Basically does the same as the checkbox option but automatically for PCSX2.

I will be uploading the update in a while. Hope you enjoy it.

**Comment by Gonckzilla** [comment]
Hey! Nice to hear from you again. I'm glad you were able to sort the issue out, thank you for looking into it :) Can't wait to test it out!

**Comment by Haruki1707** [comment]
Updated released, also included a new emulator on this release, now you can open ShortCutes to auto-updated it.

Any problem don't hesitate to open another issue.
