### ISSUE TITLE
Index was out of range. must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by Logboy2000** [Haruki1707/ShortCutes#8]
![image](https://github.com/Haruki1707/ShortCutes/assets/72185335/5dc842d9-9724-452c-b85e-ace711e2d7b5)

I'm trying to create a shortcut for Super Mario Odyssey in yuzu

File Type: XCI
Shortcutes Version: Latest from https://haruki1707.github.io/ShortCutes/

**Comment by Logboy2000** [comment]
setup before error occurs
![image](https://github.com/Haruki1707/ShortCutes/assets/72185335/ed9bc20b-ed4d-47ff-aa50-7177a92a594a)

**Comment by Logboy2000** [comment]
UPDATE: Tried making a shortcut for CEMU for breath of the wild. It only manages to load shaders and then crashes. After trying without using the shortcut it worked fine.
![image](https://github.com/Haruki1707/ShortCutes/assets/72185335/47a3307d-5cdc-4c96-a057-56ed45f129d1)

**Comment by Logboy2000** [comment]
Update Again: tried with dolphin and got the same error as yuzu
![image](https://github.com/Haruki1707/ShortCutes/assets/72185335/b7b38c96-c888-4c58-a9a5-2eaffb62035a)

**Comment by Haruki1707** [comment]
That is weird, I will check on it, seems to be a image conversion problem. But Cemu loading the shaders and then crashing seems to be a problem related to the emulator

**Comment by Haruki1707** [comment]
Can u tell me the format or either pass me the images you were using for the shortcuts. TY

**Comment by Logboy2000** [comment]
In all cases lunching directly from the emulator worked.
Here are the images
![smo-1](https://github.com/Haruki1707/ShortCutes/assets/72185335/b40391d5-8f27-48e3-b5a7-37706e670bc4)
![b9648e4dc6a5ad47bea0c9023e810dfd ico(1)](https://github.com/Haruki1707/ShortCutes/assets/72185335/fb10fcc6-56c1-4446-9d14-31c50c7130f5)
![fef30dc904979d70213ed4c220efbd77_jpg](https://github.com/Haruki1707/ShortCutes/assets/72185335/9102e408-7053-4260-8c1b-523f62177627)

**Comment by Logboy2000** [comment]
yes my discord is
Logboy#7992

**Comment by Logboy2000** [comment]
Was fixed in latest update.
